# Change the title, it's for you. Maybe you see "My newspaper"?
title: Surveyor Weekly

# Options: light, dark, sepia or clojure 
theme: light

# Options: daily, weekly or all
edition: weekly

feeds:
  - https://landsurveyorsunited.com/video/feed/all
  - https://landsurveyorsunited.com/photo/feed/all
